name: Build and deploy Node.js app with Docker and PM2 to Azure Web App - GraphQlTeam3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: actions/docker/build@v3
        with:
          file: Dockerfile
          build-args:# Optional: Pass build arguments to Dockerfile (if needed)
            # ...
          tag: ${{ secrets.DOCKERHUB_USERNAME }}/graphqlteam3:latest

      - name: Push Docker image to Docker Hub
        uses: actions/docker/push@v3
        with:
          registry: docker.hub
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ secrets.DOCKERHUB_USERNAME }}/graphqlteam3:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DC984A50342F4AC5A4F0711651EA5CFD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6D3540C68B54EEABEBC6092E6DBF60A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_834448AC8A1B4BABA32B5DFF26FD874F }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "GraphQlTeam3"
          slot-name: "Production"
          # ... (other deployment options)
          # Instead of package: ., use:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/graphqlteam3:latest
          # ... (other deployment options)
